### ISSUE TITLE
Arduino IDE Support

### ISSUE THREAD

**Issue by ozukal** [thingsboard/esp32-ota#4]
Is there any chance for this example supports Arduino IDE environment ? Thank you.

**Comment by vkukhtyn** [comment]
Hi @ozukal, 
unfortunately no, for now Arduino IDE support isn't planned. 
Just interesting, why just don't use [ESP-IDF](https://github.com/espressif/esp-idf) and any source code editor?

**Comment by ozukal** [comment]
I am in a hurry so not yet. Thank you for your reply.

**Comment by asukiaaa** [comment]
There are examples for arduino sdk.
https://github.com/thingsboard/thingsboard-arduino-sdk/blob/master/examples
